package views.enums;

public enum CityMessage {
    INVALID_NAME,
    INVALID_POSITION,
    NOT_CITY,
    SAME_TILE,
    NO_SELECTED_CITY,
    NO_PERMISSION,
    NOT_CITY_TILE,
    NO_FREE_CITIZEN,
    NOT_WORKING_TILE,
    WORKING_TILE,
    NOT_ENOUGH_GOLD,
    SUCCESS;
}
