package views.enums;

public enum CombatMessage {
    INVALID_POSITION,
    NO_COMBATABLE, 
    NO_UNIT_SELECTED, 
    OUT_OF_RANGE, 
    NOT_VISIBLE_TILE, 
    CANNOT_ATTACK_YOURSELF,
    SUCCESS, NEEDS_MELEE_UNIT, 
    NOT_PREPARED, 
    NO_MOVE_POINT,
    CITY_DESTROYED,
    CITY_ATTACHED;
}
