package views.enums;

public enum Message {
    SUCCESS,
    USERNAME_EXISTS,
    NICKNAME_EXISTS,
    LOGIN_ERROR,
    CHANGE_NICKNAME_ERROR,
    INCORRECT_PASSWORD,
    REPETITIOUS_PASSWORD,
    INVALID_POSITION,
    NO_COMBAT_UNIT,
    NO_NONCOMBAT_UNIT,
    NO_SELECTED_UNIT,
    NO_COMBAT_SELECTED_UNIT,
    NOT_ACCESSIBLE_TILE,
    FULL_TILE,
    ENEMY_BORDERS;
}
