package views.enums;

public enum UnitMessage {
    INVALID_POSITION,
    NOT_COMBAT_UNIT,
    NOT_NONCOMBAT_UNIT,
    NOT_PLAYERS_TURN,
    NO_SELECTED_UNIT,
    NOT_ACCESSIBLE_TILE,
    SAME_TARGET_TILE,
    FULL_TARGET_TILE,
    ENEMY_BORDERS,
    SUCCESS;
}
