package views.enums;

public enum Message {
    SUCCESS,
    FAILURE,
    USERNAME_EXISTS,
    NICKNAME_EXISTS,
    LOGIN_ERROR,
    CHANGE_NICKNAME_ERROR,
    INCORRECT_PASSWORD,
    REPETITIOUS_PASSWORD,
}
